version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: presupuesto_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # puerto host:contenedor
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
