version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: presupuesto_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"  # puerto host:contenedor
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
